version: '3.6'
volumes:
  shared-workspace:
    name: "Spark_Mongo1"
    driver: local
  rs11:
  rs12:
  rs13:

services:
  jupyterlab:
    image: jupyter/pyspark-notebook
    container_name: jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 9988:8888
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet
    restart: always

  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    ports:
      - 9080:8080
      - 8077:7077
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet
    restart: always

  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 9081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - localnet
    restart: always

  spark-worker-2:
    image: bde2020/spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 9082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - localnet
    restart: always

  mongo_api:
    image: mongo:latest
    command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
    ports:
      - 28117:27017
    container_name: mongo1
    volumes:
      - rs11:/data/db
    networks:
      - localnet
    restart: always

  mongo2:
    image: "mongo:latest"
    container_name: mongo2
    command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
    volumes:
      - rs12:/data/db
    networks:
      - localnet
    ports:
      - "28118:27017"
    restart: always

  mongo3:
    image: "mongo:latest"
    container_name: mongo3
    command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
    volumes:
      - rs13:/data/db
    networks:
      - localnet
    ports:
      - "28119:27017"
    restart: always

networks:
    localnet:
        attachable: true
